### ISSUE TITLE
Feature request: support loading fonts in Wasm

### ISSUE THREAD

**Issue by imanbell** [yisibl/resvg-js#115]
Hi, thanks for the great library :)

I see in the 2.0.0 changelog that "The current version of Wasm does not support loading fonts, so please submit an issue if you have a request."

Are there any plans to support loading fonts in the Wasm version in the near future? It would be useful for consistent SVG text rendering between the browser and nodejs.

Thanks!

**Comment by yisibl** [comment]
Yes, we are working on and implementing this in our spare time.

**Comment by yisibl** [comment]
We supported it in v2.5.0: https://github.com/yisibl/resvg-js/releases/tag/v2.5.0
