### ISSUE TITLE
resvg-js don't work for SVGs with HEX color containing opacity

### ISSUE THREAD

**Issue by victorcarvalhosp** [yisibl/resvg-js#124]
Hi team, first of all, thanks for making this awesome library, we've been using it without any issues so far, but today we noticed an issue that we're not being able to overcome, if we have a SVG that has some HEX color with transparency, like #FFFFFF80 for example(for 50% transparency) - it just don't work and generate an empty image. We tried with the "sharp" library and it worked well, but we don't want to use sharp.

To replicate it is quite straightforward, just get some svg with hex color containing transparency like:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="-0.625 -0.625 25.25 25.25" stroke-width="2.75" height="24" width="24"><path d="M4.117,6.97V2.25a1.5,1.5,0,0,1,1.5-1.5h6" fill="none" stroke="#f6090980" stroke-linecap="round" stroke-linejoin="round"></path><path d="M13.117,17v4.75a1.5,1.5,0,0,1-1.5,1.5h-6a1.5,1.5,0,0,1-1.5-1.5V17.03" fill="none" stroke="#f6090980" stroke-linecap="round" stroke-linejoin="round"></path><path d="M19.117.75,13.206,7.632a.375.375,0,0,0,.286.618h2.625v6l5.91-6.882a.375.375,0,0,0-.285-.618H19.117Z" fill="none" stroke="#f6090980" stroke-linecap="round" stroke-linejoin="round"></path><path d="M10.867,5.663A6.742,6.742,0,1,0,13.615,16.5" fill="none" stroke="#f6090980" stroke-linecap="round" stroke-linejoin="round"></path></svg>`

and paste it in the demo page: https://resvg-js.vercel.app/

Or try to convert it using:

`const pngImageBuffer = new Resvg(svg).render().asPng()
`
In both cases, you'll see the issue, as it will generate a file that has nothing inside. If I change the SVG removing the transparency from the HEX values it works just fine.

Am I doing something wrong? Or this is really a bug?

Thanks!

**Comment by victorcarvalhosp** [comment]
Answering my own question, it doesn't work because of the reasons below:
https://github.com/RazrFalcon/resvg/issues/518

The solution is to convert from hex to rgba on my side and then generate the png.

**Comment by yisibl** [comment]
Yes, this relies on the upstream resvg v0.23.0, which just supports the HEXA color format(PR https://github.com/RazrFalcon/svgtypes/pull/13), and I will upgrade to the latest resvg in the near future.

**Comment by zimond** [comment]
It's supported in `svgtypes`, which has nothing to do with forked code. Just publishing a new version with re-compiled artifacts will be sufficient.
