### ISSUE TITLE
background-color on svg doesn't work

### ISSUE THREAD

**Issue by victorcarvalhosp** [yisibl/resvg-js#130]
Hi team, I noticed if the svg has a style property for the background color the generated png ignores it.

How to replicate:
Copy the SVG below into https://resvg-js.vercel.app/ and you'll see the red background color is being ignored in the generated PNG:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-width="1.5px" style="background-color: red"><g transform="matrix(0.9,0,0,0.9,1.1999999999999993,1.1999999999999993)"><defs></defs><title>desktop-computer-1</title><rect x="0.75" y="4.5" width="15" height="12" rx="1.5" ry="1.5" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></rect><path d="M18.75,7.5h1.5L21.75,6a1.5,1.5,0,0,1,1.5,1.5V18a1.5,1.5,0,0,1-1.5,1.5L20.25,18h-1.5" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></path><line x1="8.25" y1="16.5" x2="8.25" y2="19.5" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></line><line x1="5.25" y1="19.5" x2="11.25" y2="19.5" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></line><line x1="20.25" y1="10.5" x2="18.75" y2="10.5" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></line><line x1="20.25" y1="13.5" x2="18.75" y2="13.5" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"></line></g></svg>`

Thanks!

**Comment by yisibl** [comment]
`background-color` is not part of the SVG specification, so resvg will not parse it.

You should use the [`background`](https://github.com/yisibl/resvg-js/blob/015a6bc3fc14011f367441a259beea6dd5e80c81/index.d.ts#L34) option provided by resvg-js to set it.
