### ISSUE TITLE
paint-order on svg doesn't work

### ISSUE THREAD

**Issue by tyutjohn** [yisibl/resvg-js#138]
I want to set margin for font, like the textStroke property of css, but it doesn't work when I use `paint-order:stroke`。This is an example on MDN
`<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200">
  <linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
    <stop stop-color="#888"/>
    <stop stop-color="#ccc" offset="1"/>
  </linearGradient>
  <rect width="400" height="200" fill="url(#g)"/>
  <g fill="crimson" stroke="white" stroke-width="6" stroke-linejoin="round"
     text-anchor="middle" font-family="sans-serif" font-size="50px" font-weight="bold">
    <text x="200" y="75">stroke over</text>
    <text x="200" y="150" paint-order="stroke" id="stroke-under">stroke under</text>
  </g>
</svg>`
I got two fonts with fill first and stroke after
So how can I set this in resvg ? This looks strange

**Comment by yisibl** [comment]
Dependent on upstream support: https://github.com/RazrFalcon/resvg/issues/422

**Comment by tyutjohn** [comment]
> 

Thanks Reply～
I will provide a PR to support it

**Comment by tyutjohn** [comment]
> > 
> 
> Thanks Reply～ I will provide a PR to support it

Status record. [paint-order](https://github.com/RazrFalcon/resvg/pull/525)

**Comment by yisibl** [comment]
@tyutjohn At the risk of asking, do you still have plans to continue to complete the upstream PR?

**Comment by tyutjohn** [comment]
> 

Of course, Maybe next week I'll have some spare time to work on it

**Comment by yisibl** [comment]
Done in #156
