### ISSUE TITLE
[Node] concurrent usage wrong speed 

### ISSUE THREAD

**Issue by Zhengqbbb** [yisibl/resvg-js#171]
`resvg-js` performance in **concurrency capabilities does not meet expectations**. It looks like a linear growth. Some places are not well ?
I am comparing the following code with [sharp](https://github.com/lovell/sharp) lib
If there are any mistakes in writing, welcome point out ～

How To Test: `time tsx test.cts`
Test Code：
```ts
// test.cts
/* eslint-disable no-console */
import { renderAsync } from '@resvg/resvg-js'
import sharp from 'sharp'

const svg = '<svg width="1200" height="628" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 628" fill="#000"><path d="M37.59.25l36.95 64H.64l36.95-64z"></path></svg>'

export async function genPNG(svg: string) {
  const render = await renderAsync(svg, {
    fitTo: {
      mode: 'width',
      value: 1200,
    },
  })
  return render.asPng()
  // return await sharp(Buffer.from(svg))
  //   .resize(1200, 630)
  //   .png()
  //   .toBuffer()
}

(async function () {
  const mock = new Array(1000).fill(null)
  console.log('`@resvg/resvg-js` Current Test Concurrent Length: ', mock.length)
  Promise.all(mock.map(_ => genPNG(svg)))
}()).catch((err) => {
  console.error(err)
  process.exit(1)
})

```

Test Screenshot:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/40693636/205816735-7fbbe924-56a3-434f-b035-440929a75054.png">

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/40693636/205816905-057925f4-a16d-48e5-b6dd-3a58d3e45110.png">

**Comment by yisibl** [comment]
`renderAsync` will be slower, please try `render`.

**Comment by Zhengqbbb** [comment]
<img width="645" alt="image" src="https://user-images.githubusercontent.com/40693636/209441848-b6000d8e-6c7a-4445-a77e-b1ecbc7f81a6.png">

Same. Not have big diff. The following is my test code, please point out if there is any problem.

```ts
import { Resvg } from '@resvg/resvg-js'

const svg = '<svg width="1200" height="628" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 628" fill="#000"><path d="M37.59.25l36.95 64H.64l36.95-64z"></path></svg>'

export async function genPNG(svg: string) {
  const render = new Resvg(svg, {
    fitTo: {
      mode: 'width',
      value: 1200,
    },
  })
  return render.render().asPng()
}

(async function () {
  const mock = new Array(1000).fill(null)
  console.log('`@resvg/resvg-js` Current Test Concurrent Length: ', mock.length)
  Promise.all(mock.map(_ => genPNG(svg)))
}()).catch((err) => {
  console.error(err)
  process.exit(1)
})
```

**Comment by Brooooooklyn** [comment]
@Zhengqbbb what kind of growth curve do you expect? You can set `UV_THREADPOOL_SIZE=YOUR_CPU_CORE_COUNTS` to increase `libuv` thread pool size to make the angle of the linear curve smaller, but it will still be linear because generating PNG from SVG is CPU sensitive job, and it will always occupy all of your CPU times.

**Comment by Zhengqbbb** [comment]
> but it will still be linear because generating PNG from SVG is CPU sensitive job, and it will always occupy all of your CPU times.

Ok, I am more curious why [sharp lib](https://github.com/lovell/sharp) can suppress the curve very well, maybe there is a better possibility to optimize the conversion speed.
