### ISSUE TITLE
Compatible with Electron 21+ / V8's Memory Cage?

### ISSUE THREAD

**Issue by hrueger** [yisibl/resvg-js#174]
Hi,
I couldn't find any info on whether this is compatible with the [Memory Cage of Electron 21+](https://www.electronjs.org/blog/v8-memory-cage). Is it?
I just don't want to risk that it works on my machine and users of my application are doing something differently and it crashes for them.

**Comment by yisibl** [comment]
I'm sorry, I don't know much about this.

**Comment by hrueger** [comment]
I just found this, maybe it gives a clue?
https://github.com/napi-rs/napi-rs/issues/1346

**Comment by yisibl** [comment]
Maybe you can follow this issue: https://github.com/nodejs/node-addon-api/issues/1257

**Comment by eexit** [comment]
Hello, I'm trying to use this lib inside an electron app and it gives me this error: 

```
(node:69164) UnhandledPromiseRejectionWarning: Error: Failed to create napi buffer
```

So I believe it's not compatible.

**Comment by Brooooooklyn** [comment]
@yisibl release a new version with the latest NAPI-RS would solve this problem

**Comment by eexit** [comment]
Thanks! 🎉
