### ISSUE TITLE
Error: `No loader is configured for ".node" files: node_modules/@resvg/resvg-js-linux-x64-musl/resvgjs.linux-x64-musl.node` with Vite 4 and Netlify

### ISSUE THREAD

**Issue by sw-yx** [yisibl/resvg-js#175]
Hi, apologies if this is the wrong repo for this error but I am following https://geoffrich.net/posts/svelte-social-image/ and it works locally, but fails when I try to deploy to Netlify:

![image](https://user-images.githubusercontent.com/6764957/206884727-827beb0a-109c-4e94-959c-e77eee5a1629.png)

Full error message

```
10:10:26 PM: ✘ [ERROR] No loader is configured for ".node" files: node_modules/@resvg/resvg-js-linux-x64-musl/resvgjs.linux-x64-musl.node
10:10:26 PM:     node_modules/@resvg/resvg-js/js-binding.js:1:2980:
10:10:26 PM:       1 │ ...Binding=require("@resvg/resvg-js-linux-x64-musl")}catch(e){loadE...
10:10:26 PM:         ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10:10:26 PM: ✘ [ERROR] No loader is configured for ".node" files: node_modules/@resvg/resvg-js-linux-x64-gnu/resvgjs.linux-x64-gnu.node
10:10:26 PM:     node_modules/@resvg/resvg-js/js-binding.js:1:3212:
10:10:26 PM:       1 │ ...eBinding=require("@resvg/resvg-js-linux-x64-gnu")}catch(e){loadE...
10:10:26 PM:         ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm not sure where this message comes from but you can see the error in this branch https://github.com/sw-yx/swyxkit/tree/addOgimage when deployed to Netlify: https://app.netlify.com/sites/swyxkit/deploys/63954a072248cf0008f384ae

blocking https://github.com/sw-yx/swyxkit/pull/145 right now with this error message

**Comment by sw-yx** [comment]
I discovered and tried https://github.com/evanw/esbuild/issues/1051 but unfortunately it didnt change anything

**Comment by Brooooooklyn** [comment]
try `esbuild YOUR_ENTRY --platform=node --loader:.node=file --outdir=dist`

**Comment by yisibl** [comment]
Thanks to @Brooooooklyn for the answer.

**Comment by sw-yx** [comment]
thank you - closing for now until i can try this again

**Comment by unculture** [comment]
@sw-yx  I have satori->resvg-js working on Netlify by adding this to the `netlify.toml` for the functions.

`external_node_modules = ['@resvg/resvg-js']`

**Comment by unculture** [comment]
@sw-yx I have resvg-js working on Netlify with SVG from Satori using the following in my `netlify.toml`

```
[functions]
external_node_modules = ['@resvg/resvg-js']
```

**Comment by bartosjiri** [comment]
For anyone having this issue with the library while using the `@sveltejs/adapter-node` adapter in Svelte(Kit):

- Make sure to have the `@resvg/resvg-js` library installed as a dependency (not devDependency); `package.json`:
  ```json
  {
    "scripts": {
      "build": "vite build",
    },
    "devDependencies": {
      "@sveltejs/adapter-node": "^1.2.3",
      "vite": "^4.2.0"
    },
    "dependencies": {
      "@resvg/resvg-js": "^2.4.1"
    },
    "type": "module"
  }
  ```
- Specify the `@resvg/resvg-js` library as external dependency in the `vite.config.(js|ts)` file:
  ```ts
  import { sveltekit } from '@sveltejs/kit/vite';
  import { defineConfig } from 'vite';

  export default defineConfig({
    plugins: [
      sveltekit()
    ],
    build: {
      rollupOptions: {
        external: ['@resvg/resvg-js'],
      }
    }
  });
  ```

**Comment by taverasmisael** [comment]
@antoniods, sad to hear that. Ultimately, I had to deploy to Vercel instead, not because of this, but because I was having issues at the build stage with the `experimental.assets` [adding a top-level await](https://github.com/taverasmisael/taverasmisael.com/pull/1#issuecomment-1565549015).

I did change the config to add `resvg/resvg-js` as external/exclude in other places.

This is my current configuration, and it worked on Netlify, but the build step failed because of the `experimental.assets`.

```js
export default defineConfig({
    ssr: { external: ["@resvg/resvg-js"] },
    optimizeDeps: { exclude: ["@resvg/resvg-js"] },
    build: { rollupOptions: { external: ["@resvg/resvg-js"] } },
  },
})
```

**Comment by antoniods** [comment]
> ...., I had to deploy to Vercel instead, not because of this, but because I was having issues at the build stage with the `experimental.assets` [adding a top-level await](https://github.com/taverasmisael/taverasmisael.com/pull/1#issuecomment-1565549015).

Build stage works perfectly on vercel, no more issues with and resvg-js in my case. Thanks @taverasmisael

**Comment by laneparton** [comment]
This was helpful to landing at:

**astro.config.mjs**
```
  vite: {
    ssr: {
      external: ['@resvg/resvg-js']
    },
    optimizeDeps: {
      exclude: ["@resvg/resvg-js"]
    }
  }
```

With:
```
  "dependencies": {
    "astro": "^3.0.8",
  },
  "devDependencies": {
    "@resvg/resvg-js": "^2.4.1",
  }
 ```

**Comment by kylesloper** [comment]
> > Thanks @bartosjiri this worked perfectly. I'm using Astro, so the place to declare external dependencies is on the `astro.config.mjs`, very similar
> > ```js
> > export default defineConfig({
> >   vite: {
> >     ssr: { // ssr instead of rollupOptions
> >       external: ['@resvg/resvg-js']
> >     }
> >   }
> > })
> > ```
> 
> Thanks for sharing it but your snippet didn't solve the issue with Astro for me. It's still impossible using resvg-js on Netlify and i'm get an error in the building step.

Hey @antoniods, Did you manage to get this working with Netlify. It's pretty unbelievable this still isn't working
