### ISSUE TITLE
Example image is inappropriate

### ISSUE THREAD

**Issue by moonwave99** [yisibl/resvg-js#177]
I am pretty sure the library works as good without a sexualised image:

![Example image](https://github.com/yisibl/resvg-js/raw/main/example/out-resvg-js.png)

**Comment by zimond** [comment]
It's reasonable. Do you happen to have any free SVG file at hand that we could use to replace this one? Thanks.

**Comment by yisibl** [comment]
This SVG is complex enough that it is mainly used to compare the rendering results of different engines.

I agree to remove it from Readme.md, but keep the code in the example JS.
