### ISSUE TITLE
Update resvg to 0.28.0?

### ISSUE THREAD

**Issue by edgars-vasiljevs** [yisibl/resvg-js#190]
Hello

Would it be possible to update resvg to latest version 0.28.0? 

Thanks for doing great work.

**Comment by zimond** [comment]
Sure! A patch is coming

**Comment by yisibl** [comment]
resvg 0.28.0 made a lot of API changes, in particular the removal of the ability to write SVGs, and we needed to make some changes at the Rust level.

This was a huge task, and many thanks to zimond for his efforts!
