### ISSUE TITLE
rust error when converting svg

### ISSUE THREAD

**Issue by isaacfink** [yisibl/resvg-js#192]
the full trace is this

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParsingFailed(ParserError(InvalidElement(InvalidName, TextPos { row: 1, col: 119 })))', /Users/runner/.cargo/git/checkouts/resvg-4b7e4ee32ad6d954/7c98ad6/src/image.rs:24:102
```

I am generating the svg using satori, this is the generated svg file I am trying to convert

![thumbnail](https://user-images.githubusercontent.com/46644190/214847483-b8922eb3-64f5-4c0e-893b-8437893b9b25.svg)

you can see the text on top it says text this is the line that causes issues, although I don't really understand why, maybe I need to load the font? but it should be converted to paths from satori?

When I generate an image without text it works perfectly so I am pretty sure this is it but I don't know why it happens and I don't understand rust so I can't check the trace for more clues

**Comment by isaacfink** [comment]
I am also getting this error

```
admin:dev: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
admin:dev: fatal runtime error: failed to initiate panic, error 5
```

which means it crashes my app but it doesn't exit the execution so it doesn't automatically restart

**Comment by isaacfink** [comment]
I am closing this issue since the problem was resolved but it might be a good idea to handle this gracefully without crashing anything, I believe this depends on the runtime environment so might not be so straight forward

**Comment by zimond** [comment]
Indeed, I'll see what we can do
