### ISSUE TITLE
Wrong generation into PNG(need support mask-type)

### ISSUE THREAD

**Issue by tarasom** [yisibl/resvg-js#205]
During convertation from SVG to PNG I lost some context of my image (red and grey colors):
[Source](https://github.com/dicebear/dicebear/blob/main/packages/%40dicebear/bottts-neutral/src/components/eyes.ts#L25):
 ![text](https://user-images.githubusercontent.com/1064620/217540631-296d7c16-a41f-4750-bf34-35f15ffec890.svg)

Target: 
![text-out](https://user-images.githubusercontent.com/1064620/217540732-af1290e8-b3b9-4048-af41-f09d9e0acbbd.png)

On the other hand everything is ok if I generate similar image
[Source](https://github.com/dicebear/dicebear/blob/main/packages/%40dicebear/bottts-neutral/src/components/eyes.ts#L20):
![text](https://user-images.githubusercontent.com/1064620/217541914-ac37aa5d-61d2-44e7-860a-7667455d7b45.svg)

Target:
![text-out](https://user-images.githubusercontent.com/1064620/217541958-94bc577a-180e-42ac-a825-2b11a089a635.png)

Could you help me to identify what is a root cause of that. Is this really an issue with library or there some limitations. Thanks!

**Comment by yisibl** [comment]
I also lost the color when I opened it directly in the browser.

Please go upstream to the repository and submit feedback and attach the svg string directly to the issue, thanks.
https://github.com/RazrFalcon/resvg/issues

**Comment by yisibl** [comment]
The `mask-type` is already supported in upstream resvg v0.32, some work is needed in resvg-js to upgrade to the latest version.

https://github.com/RazrFalcon/resvg/blob/master/CHANGELOG.md#0320---2023-04-23
