### ISSUE TITLE
Font is no longer rendered since version 2.4

### ISSUE THREAD

**Issue by FlorianKoerner** [yisibl/resvg-js#207]
I updated to the new version 2.4, but the fonts are no longer rendered. It works in version 2.3.

My code:
https://github.com/dicebear/dicebear/blob/main/packages/%40dicebear/converter/src/node/core.ts#L69-L89

First reported:
https://github.com/dicebear/dicebear/issues/281

**Comment by FlorianKoerner** [comment]
Also seems to affect the example in the readme.

![image](https://user-images.githubusercontent.com/647303/218271646-e11c52b9-be2a-43f3-8f37-c563d394a025.png)

**Comment by yisibl** [comment]
I'm sorry, I'll look into this.

**Comment by yisibl** [comment]
@FlorianKoerner I have released 2.4.1, please try it. Thanks!

**Comment by FlorianKoerner** [comment]
@yisibl Works great! Thanks for the quick fix. 🥳
