### ISSUE TITLE
text is not added when using this library, it works fine when using resvg directly from terminal

### ISSUE THREAD

**Issue by isaacfink** [yisibl/resvg-js#210]
i am assuming I am doing something wrong with fonts, in any case here is a [link](https://fromsmash.com/xQbiXC-n6M-bt) to the svg I tried to convert, this is my configuration
```
const options = {
	background: 'rgba(0, 0, 0, 0.0)',
	font: {
		fontFiles: [
			'https://ubexuegkqzaitvqqwbeq.supabase.co/storage/v1/object/public/fonts/Chadva.ttf',
			...this.fontUrls
		], // Load custom fonts.
		loadSystemFonts: false, // It will be faster to disable loading system fonts.
		defaultFontFamily: 'Pirate Scroll'
	}
};

const resvg = new Resvg(src, options).render().asPng();
```
I am getting an (almost) perfect image but without any of the text, `this.fontUrls` is a list of remote fonts, everything is either ttf or otf
the svg is generated by a function that generates a string, so I did run into some issues before where the svg was simply corrupt but this one specifically seems like it's not and it works in chrome and with resvg

**Comment by isaacfink** [comment]
when suing resvg from the command line it si also the wrong font but it adds some text

**Comment by zimond** [comment]
`fontFiles` only support local file path now, you need to download the fonts first

**Comment by isaacfink** [comment]
How can I reference the font in the svg?

**Comment by isaacfink** [comment]
Sorry if this is a basic question but I'm used to working with css fonts, it might be relevant that I am not really in control of how the font files are named (custom fonts that users upload)

**Comment by zimond** [comment]
The problem here is that currently neither `resvg` nor `resvg-js` download font from a url. So you need to download the font first and provide a local path in the option `fontFIles`. So it really doesn't matter what the files are named, as long as it is provided everything is OK. We are using attributes in the font file (font name, family, weights, etc) to match a font when rendering, if you are curious.

**Comment by isaacfink** [comment]
So I asked the person uploading the fonts to name the files just like the font so I can deduct the name from the file path, I didn't know font files have a name I thought it's whatever you give it in font face, thanks

**Comment by yisibl** [comment]
I guess your confusion is: don't know the font-family of the URL corresponding to the font, right?

If so, I have a PR that is solving this problem by only needing the fontFiles parameter and can do without the defaultFontFamily parameter. resvg-js will read the font-family from the font file and set it to SVG.

**Comment by isaacfink** [comment]
It works now, I am using a package to read the font names from the font file itself, It's not ideal because that package is not type safe but it works, I am running into a different issue now, with hebrew characters, is it not supported?

**Comment by zimond** [comment]
Please open a new issue with a test case
