### ISSUE TITLE
Possible Bug with v2.4

### ISSUE THREAD

**Issue by DSalman** [yisibl/resvg-js#214]
Hello. Using v2.4 (and 2.4.1) I'm getting blank pngs. Everything was working quite well until I did some updating. I traced it to the resvg-js package and found that if I reverted back to 2.3 everything worked nicely once again. My code is pretty much boilerplate:

let svg = fs.readFileSync(fname+".svg");
const opts = {
            fitTo: {
                mode: 'width',
                value: 720,
            },
            font: {
                fontDirs: [fontFolder], 
                loadSystemFonts: false
            }   
        } 
const resvg = new Resvg(svg, opts);
        const pngData = resvg.render();
        const pngBuffer = pngData.asPng();

        fs.writeFileSync(fname+".png", pngBuffer);

I'm seeing this on an M1 Macbbook as well as Linux (amd64). Haven't tried Windows.
I'm attaching a sample of the svg frames and the font which gets copied to "fontFolder". At first I thought it was a missing font issue but as you can see not even the blue background is rendered. Thanks!
[version2.4issue.zip](https://github.com/yisibl/resvg-js/files/10855284/version2.4issue.zip)

**Comment by yisibl** [comment]
I think it has nothing to do with the font, it seems to be caused by the transform property on the SVG. When the `transform: translate3d(0,0,0)` is removed, everything works fine.

Here is a regression use case:

```
 <svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200"  style="transform: translate(10px, 10px);">
     <rect width="200" height="200" fill="green" />
  </svg>
```

Expected: A green square is seen, but is currently transparent.

Trying to test directly with resvg also reports an error, so this is an upstream issue.

```bash
cargo run --release -- --width 300 tests/svg/e-path-053.svg tests/png/e-path-053.png
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/resvg --width 300 tests/svg/e-path-053.svg tests/png/e-path-053.png`
Warning (in rosvgtree:303): Failed to parse transform value: 'translate(10px, 10px)'.
```

**Comment by DSalman** [comment]
I don't control the generation of the svgs, they are created by Lottie which you may or may not be familiar with. I will make a quick patch to parse & remove that transform so I can test against 2.4.

Just to be clear, is it the empty transform or the fact that its 3d? I did a quick search and found some questions surrounding the support for translate3d usage in svgs - its not official but kind of a future thing. Maybe I should suggest the Lottie developers remove it?

**Comment by yisibl** [comment]
translate3d(0, 0, 0) used to be a hack that triggered GPU acceleration in the browser. but it's not needed in resvg anyway, so you can remove it manually first.


1. `translate3d()` is not part of the SVG specification
  > For example, for a scaleX(…) or translate3d(…) transform, [SVG_TRANSFORM_UNKNOWN](https://svgwg.org/svg2-draft/coords.html#__svg__SVGTransform__SVG_TRANSFORM_UNKNOWN) would be returned.
2. As of SVG2, transform is a presentation attribute, meaning it can be used as a CSS property. However, be aware that there are some differences in syntax between the CSS property and the attribute.
  For example, the SVG syntax is: `translate(10, 10)`, while CSS is `translate(10px, 10px)`.


In general, I'd like resvg upstream to revert to the previous behavior and skip it when it encounters an unsupported transform syntax.

**Comment by DSalman** [comment]
Thanks for clearing that up.
