### ISSUE TITLE
希望提供只加载一次系统字体的能力

### ISSUE THREAD

**Issue by WgCg** [yisibl/resvg-js#215]
你好，我的需求是开发一个nodejs图片生成服务，里面使用到了resvg-js将svg转成图片，但是每次处理请求将svg转图片时，resvg-js都需要重新加载一次系统字体，导致接口耗时较长，我想要在启动服务时只加载一次系统字体，后续在接口处理过程中不用再重新加载，请问是否能提供这样的功能呢

**Comment by yisibl** [comment]
目前没有时间做。
你可以先只加载 SVG 中需要的字体，这样速度要快很多。
