### ISSUE TITLE
能不能支持转jpg

### ISSUE THREAD

**Issue by ppjjzz** [yisibl/resvg-js#228]
png有点大，能否支持svg转jpg？

**Comment by yisibl** [comment]
这个项目的首要目标是输出无损的位图格式，jpeg 的优先级不高。

不过 @Brooooooklyn 有一个分支支持输出 jpeg，你可以编译试试：https://github.com/yisibl/resvg-js/tree/jpeg

**Comment by zimond** [comment]
你可以用 `RenderedImage::pixels()`  这个API拿到RGBA buffer(Uint8Array)，然后随便用什么库去encode
