### ISSUE TITLE
文本无法渲染

### ISSUE THREAD

**Issue by muyichuanqi** [yisibl/resvg-js#250]
const { Resvg } = require('@resvg/resvg-js')

let svg = `
<svg version="1.2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720" width="1280" height="720">
	<title>template</title>
	<style>
		tspan { white-space:pre } 
		.s0 { fill: #daf2d9 } 
		.s1 { fill: #94d891 } 
		.t2 { font-size: 30px;fill: #1a1a1a;font-weight: 400;font-style: italic;font-family: "DejaVuSansCondensed-Oblique", "DejaVu Sans Condensed" } 
		.t3 { font-size: 76px;fill: #1a1a1a;font-weight: 275;font-family: "BioRhymeExpanded-ExtraLight", "BioRhyme Expanded" } 
	</style>
	<path id="Background" class="s0" d="m0 0h1280v720h-1280z"/>
	<g id="Border-right">
		<g id="dots">
			<path id="Layer" class="s1" d="m1214.6 214.2c0-13.9 11.2-25 25.1-25 13.9 0 25 11.1 25 25 0 13.9-11.1 25.1-25 25.1-13.9 0-25.1-11.2-25.1-25.1zm-162.7 164.2c0-14 11.1-25.1 25-25.1 13.9 0 25.1 11.1 25.1 25.1 0 13.9-11.2 25-25.1 25-13.9 0-25-11.1-25-25zm161.3 357.4c0-13.9 11.2-25 25.1-25 13.9 0 25 11.1 25 25 0 13.9-11.1 25.1-25 25.1-13.9 0-25.1-11.2-25.1-25.1zm-73.7 232.3c0-13.9 11.1-25 25-25 14 0 25.1 11.1 25.1 25 0 13.9-11.1 25.1-25.1 25.1-13.9 0-25-11.2-25-25.1zm13.9 324.1c0-13.9 11.1-25 25.1-25 13.9 0 25 11.1 25 25 0 13.9-11.1 25.1-25 25.1-14 0-25.1-11.2-25.1-25.1z"/>
			<path id="Layer" class="s1" d="m1110.3 91.8c0-13.9 11.1-25 25-25 13.9 0 25.1 11.1 25.1 25 0 13.9-11.2 25-25.1 25-13.9 0-25-11.1-25-25zm93.2 338c0-13.9 11.1-25 25-25 13.9 0 25.1 11.1 25.1 25 0 13.9-11.2 25.1-25.1 25.1-13.9 0-25-11.2-25-25.1zm-173.9 662.1c0-13.9 11.1-25 25.1-25 13.9 0 25 11.1 25 25 0 13.9-11.1 25.1-25 25.1-14 0-25.1-11.2-25.1-25.1zm45.9-453.4c0-13.9 11.2-25.1 25.1-25.1 13.9 0 25 11.2 25 25.1 0 13.9-11.1 25-25 25-13.9 0-25.1-11.1-25.1-25zm137.7 489.6c0-13.9 11.2-25 25.1-25 13.9 0 25 11.1 25 25 0 13.9-11.1 25-25 25-13.9 0-25.1-11.1-25.1-25z"/>
			<path id="Layer" class="s1" d="m968.4 541.1l-8.3 29.2z"/>
		</g>
	</g>
	<g id="Border-left">
		<g id="dots">
			<path id="Layer" class="s1" d="m65.4 214.2c0-13.9-11.2-25-25.1-25-13.9 0-25 11.1-25 25 0 13.9 11.1 25.1 25 25.1 13.9 0 25.1-11.2 25.1-25.1zm162.7 164.2c0-14-11.1-25.1-25-25.1-13.9 0-25.1 11.1-25.1 25.1 0 13.9 11.2 25 25.1 25 13.9 0 25-11.1 25-25zm-161.3 357.4c0-13.9-11.2-25-25.1-25-13.9 0-25 11.1-25 25 0 13.9 11.1 25.1 25 25.1 13.9 0 25.1-11.2 25.1-25.1zm73.7 232.3c0-13.9-11.1-25-25-25-14 0-25.1 11.1-25.1 25 0 13.9 11.1 25.1 25.1 25.1 13.9 0 25-11.2 25-25.1zm-13.9 324.1c0-13.9-11.1-25-25.1-25-13.9 0-25 11.1-25 25 0 13.9 11.1 25.1 25 25.1 14 0 25.1-11.2 25.1-25.1z"/>
			<path id="Layer" class="s1" d="m169.7 91.8c0-13.9-11.1-25-25-25-13.9 0-25.1 11.1-25.1 25 0 13.9 11.2 25 25.1 25 13.9 0 25-11.1 25-25zm-93.2 338c0-13.9-11.1-25-25-25-13.9 0-25.1 11.1-25.1 25 0 13.9 11.2 25.1 25.1 25.1 13.9 0 25-11.2 25-25.1zm173.9 662.1c0-13.9-11.1-25-25.1-25-13.9 0-25 11.1-25 25 0 13.9 11.1 25.1 25 25.1 14 0 25.1-11.2 25.1-25.1zm-45.9-453.4c0-13.9-11.2-25.1-25.1-25.1-13.9 0-25 11.2-25 25.1 0 13.9 11.1 25 25 25 13.9 0 25.1-11.1 25.1-25zm-137.7 489.6c0-13.9-11.2-25-25.1-25-13.9 0-25 11.1-25 25 0 13.9 11.1 25 25 25 13.9 0 25.1-11.1 25.1-25z"/>
			<path id="Layer" class="s1" d="m311.6 541.1l8.3 29.2z"/>
		</g>
	</g>
	<text id="What a beautiful day." style="transform: matrix(1,0,0,1,640,408.64)" >
		<tspan x="-144.3" y="0" class="t2">What a beautiful day.
</tspan>
	</text>
	<text id="Hello World!" style="transform: matrix(1,0,0,1,640,363.04)" >
		<tspan x="-407.4" y="0" class="t3">Hello World!
</tspan>
	</text>
</svg>
`

const pngTest = async function(){
    console.log('运行')
    const resvg = new Resvg(svg, {
        font: {
            loadSystemFonts: false, // It will be faster to disable loading system fonts.
        },
        logLevel: 'off',
    });

    console.log(resvg);

    const pngData = resvg.render();
    const buffer = pngData.asPng();
    await fs.writeFile(Config.uploadUrl +'/123456.png', buffer);

}

**Comment by muyichuanqi** [comment]
linux 环境下

**Comment by muyichuanqi** [comment]
![image](https://github.com/yisibl/resvg-js/assets/12714782/7bdd3e6e-0c51-4f44-9a77-f00546df8f71)

**Comment by muyichuanqi** [comment]
![image](https://github.com/yisibl/resvg-js/assets/12714782/8b7b1927-bb14-45ec-af45-af3c7a37603e)

**Comment by muyichuanqi** [comment]
最下面使用的是官网提供的在线地址，做的测试，svg也是官方提供的演示，也是无法渲染字体，请看一下

**Comment by yisibl** [comment]
在线演示是 Wasm 的，暂时没有添加任何字体文件，等待后续 PR 实现。

Node.js 中，你需要手动引入需要的字体文件，并通过 defaultFontFamily 默认的字体 family，这个 family 对应字体的实际家族名称。

如果 loadSystemFonts 设为了 false，并且没有引入任何其他字体，将会没有任何可供 resvg-js 渲染文本的字体。 

详见示例文件：

https://github.com/yisibl/resvg-js/blob/a7918daa8889f6745d8cd6b6d83a16b22010368a/example/text.js#L16-L23

推荐测试的时候将 logLevel 选项设为 `'debug'`，可以查看加载了哪些字体。
