### ISSUE TITLE
Build error in electron with electron-react-boilerplate

### ISSUE THREAD

**Issue by sergiop** [yisibl/resvg-js#251]
Hi,
I'm trying to use resvg-js in a Electron project created with [electron-react-boilerplate](https://electron-react-boilerplate.js.org/) and I get this error during the build process:

<img width="1364" alt="Screenshot 2023-08-20 at 15 37 42" src="https://github.com/yisibl/resvg-js/assets/2235134/e3b14861-4f92-4d8d-af42-c6d944fee602">

Probably similar to this one: https://github.com/yisibl/resvg-js/issues/198

I tried adding an external to the webpack config without success:
```
externals: {
  '@resvg/resvg-js': {
    commonjs: '@resvg/resvg-js',
  },
},
```

I also tried with `node-loader` ...but nothing.
https://github.com/lovell/sharp/issues/2350#issuecomment-1150498247

Any clue?

**Comment by yisibl** [comment]
Please provide a verifiable GitHub repository.

**Comment by sergiop** [comment]
@yisibl there it is:

https://github.com/sergiop/electron-react-boilerplate-resvg-js

I used `resvg-js` in [src/main/tray.ts](https://github.com/sergiop/electron-react-boilerplate-resvg-js/blob/main/src/main/tray.ts#L45) to generate a png image from a svg code, using it as a tray icon. The tray icon is initialised in [src/main/main.ts at line 122](https://github.com/sergiop/electron-react-boilerplate-resvg-js/blob/main/src/main/main.ts#L122).

To build -> `npm run package`

Thank you so much for any advice!

**Comment by yisibl** [comment]
I tried to add the following configuration to the webpack config file, and it works.

https://github.com/sergiop/electron-react-boilerplate-resvg-js/blob/c0a3dd18403471afea87b21c7c80c532c1bdbc52/.erb/configs/webpack.config.main.prod.ts#L18

```js
  externals: {
    '@resvg/resvg-js': '@resvg/resvg-js'
  },
```

See webpack doc: https://webpack.js.org/configuration/externals/

**Comment by sergiop** [comment]
Don't ask me why, I was trying to add it to `webpack.config.renderer.prod.ts` and obviously it didn't work.
I feel really stupid asked your help for this simple issue, sorry for that and thank you! 😄

**Comment by sergiop** [comment]
Solved

**Comment by yisibl** [comment]
It doesn't matter. But I got an error opening `ElectronReact.app` in the build, can you open it?

![image](https://github.com/yisibl/resvg-js/assets/2784308/ec5831bc-8c17-4309-8f96-ad0d1fb7789c)

**Comment by sergiop** [comment]
Yes, as reported here https://github.com/lovell/sharp/issues/2350#issuecomment-1150498247, using `external` simply won't include the module into the build. So the build passes, but when you start the app, it searches for a module that is missing and it throws the error.

Finally I solved installing `node-loader`, adding the proper configuration in `.erb/configs/webpack.config.main.prod.ts`.

```javascript
module: {
  rules: [
    {
      test: /\.node$/,
      use: 'node-loader',
    },
  ],
},
```
