### ISSUE TITLE
Fails to include base64 encoded <image> in png output

### ISSUE THREAD

**Issue by zolrath** [yisibl/resvg-js#291]
Hello!
When trying to create an OpenGraph image I'm generating an svg with Satori and then attempting to convert it to a .png using resvg-js.

I need to use a base64 encoded image as the background but when I export the png with resvg-js the image does not appear.

## svg before export:
![image](https://github.com/yisibl/resvg-js/assets/454563/704f808f-ec4d-466b-a59d-42b21b52f6d8)

## png after export
![image](https://github.com/yisibl/resvg-js/assets/454563/a9158c78-d041-4ee0-99b3-8936131cfb5a)

I've zipped the svg to prevent github from doing any hijinks with it when embedding it in the issue:
[missing_image.zip](https://github.com/yisibl/resvg-js/files/14004773/missing_image.zip)

I'm running:
```ts
  const resvg = new Resvg(svg)
  return resvg.render().asPng();
```

Let me know if you need anything else!

**Comment by zolrath** [comment]
Ah, looks like I had quotes around `image/png` for some reason, making the image malformed:  `data:'image/png';base64,base64imagecharacters`

Though interestingly enough browsers seem to be able to handle that when rendering the image, even if resvg cannot.

**Comment by yisibl** [comment]
Interesting, if there is a specification that explicitly states that adding quotes is allowed, I might consider supporting it.
