### ISSUE TITLE
Drop shadow lost on render to png

### ISSUE THREAD

**Issue by razzeee** [yisibl/resvg-js#317]
I'm currently creating a svg on the fly with a `filter` specifically `drop-shadow`, but it doesn't seem to reach the png when rendering it to png.

You can find my code here https://github.com/flathub-infra/website/pull/2771

Do you think this might be a problem in resvg itself?

**Comment by yisibl** [comment]
Please provide a static SVG code that can be reproduced.

**Comment by razzeee** [comment]
![repro](https://github.com/yisibl/resvg-js/assets/5943908/f9111a32-4b7b-45e0-8809-bb3cec54ee05)

Let me know if this is not what you asked for :)

**Comment by yisibl** [comment]
You're using `style="filter:drop-shadow(0 40px 30px rgba(0, 0, 0, 42))"`, and I'm not sure if the upstream resvg supports this CSS syntax. Usually, if a feature doesn't work, you need to look for the SVG syntax.

For example: filter="drop-shadow(blue 4 5 6)", see https://raw.githubusercontent.com/RazrFalcon/resvg/5b97397af1bc995f849b274118039afa6f4d1ee3/crates/resvg/tests/tests/filters/filter-functions/drop-shadow-function.svg

This is beyond the scope of resvg-js, you can try submitting an issue upstream.

**Comment by razzeee** [comment]
Thank you
