### ISSUE TITLE
Couldn't find any versions for "@resvg/resvg-js-darwin-x64" that matches "2.6.1"

### ISSUE THREAD

**Issue by zymon** [yisibl/resvg-js#319]
Hello,
I'm getting this error when @resvg/resvg-js is installed via indirect dependency on linux machine.

@eui/tools@6.14.19 => svg-sprite@2.0.2 => @resvg/resvg-js-darwin-x64@2.6.1

Best regards,
Szymon

**Comment by yuri-ellfort** [comment]
I faced the same problem.
The original lib has version 2.6.1, but the last version of @resvg/resvg-js-darwin-x64 is 2.6.0
It seems like this version was forgotten to be updated.

<img width="457" alt="image" src="https://github.com/yisibl/resvg-js/assets/16916744/b61f0411-b80a-4f82-a22d-f726d1df4bb5">

**Comment by yhagus** [comment]
I tried using npm install instead of yarn install and it worked for now

**Comment by yisibl** [comment]
I found the problem and am working on it.

**Comment by yisibl** [comment]
Done in: https://github.com/yisibl/resvg-js/pull/320
