### ISSUE TITLE
[question] using directly an SVGSVGElement created with other code

### ISSUE THREAD

**Issue by dawadam** [yisibl/resvg-js#335]
Is it possible to directly use an SVGSVGElement created with other code?
Otherwise I need to serialize for parsing, not really efficient.

**Comment by dawadam** [comment]
I found a alternative solution here : https://talk.observablehq.com/t/generate-static-png-or-svg-at-build-time-with-framework/8833/2

```
// chart is a SVGSVGElement
new Resvg(chart.outerHTML, {
    fitTo: {
      mode: "width",
      value: 2 * chart.getAttribute("width")
    }
  })
    .render()
    .asPng();
```

**Comment by yisibl** [comment]
Yes, you need to add the xmlns namespace for resvg-js to render.

**Comment by dawadam** [comment]
Other solution, using XMLSerializer.
Reference can be found directly inside SVGSVGElement instance, like this : 
"chart" is a SVGSVGElement instance.

```
// xml serializer
const serializer = new chart.ownerDocument.defaultView.XMLSerializer();

// svg string (with xmlns namespace)
const svgString = serializer.serializeToString(chart);

// create resvg instance (using outerHTML)
const instance = new Resvg(svgString)

// png conversion
const pngBuffer = instance.render().asPng();

```

**Comment by yisibl** [comment]
Thank you for sharing.
