### ISSUE TITLE
Playground background value support alpha

### ISSUE THREAD

**Issue by maczyt** [yisibl/resvg-js#336]
https://resvg-js.vercel.app/ Can the Playground background support alpha configuration?

**Comment by yisibl** [comment]
Do you want the background to show as a checkerboard pattern representing translucency?

![image](https://github.com/yisibl/resvg-js/assets/2784308/61045817-8a0b-4f27-ab25-a4a0f5ba10e1)

**Comment by maczyt** [comment]
No, I just hope the color selector can set the alpha value. I think resvg supports rgba. just like it: 
<img width="242" alt="image" src="https://github.com/yisibl/resvg-js/assets/12051958/de9f6a9d-081f-48e0-a588-455ce2ec8d39">

**Comment by yisibl** [comment]
Currently we use the color picker provided by the browser's `<input type="color">`. Can you file a bug with Chrome? https://issues.chromium.org/issues/wizard

Also, I'll try to write a function to set the alpha on the page.

**Comment by maczyt** [comment]
According to the [mdn document](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color), this should provide color selection for the simplest purpose. Thank you for your reply.
<img width="788" alt="image" src="https://github.com/yisibl/resvg-js/assets/12051958/c847d347-087b-4033-997e-3686ffad16fa">

**Comment by yisibl** [comment]
@maczyt Regarding the alpha picker, the HTML specification is still under [discussion](https://github.com/whatwg/html/issues/3400).

I've added a custom implementation to the main branch, which I hope you'll like.

**Comment by maczyt** [comment]
> @maczyt Regarding the alpha picker, the HTML specification is still under [discussion](https://github.com/whatwg/html/issues/3400).
> 
> I've added a custom implementation to the main branch, which I hope you'll like.

It looks fantastic，appreciate it
