### ISSUE TITLE
Unable to compile binaries / LinkError: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by David-Development** [yisibl/resvg-js#358]
When I try to build the repo myself (on main) using `npm run build:wasm` it will generate a new `wasm/index_bg.wasm` file. Unfortunately when I include this file in my web project I get the following error: `LinkError: WebAssembly.instantiate(): Import #0 "wbg" "__wbg_new_70a2f23d1565c04c": function import requires a callable`. I saw that there was a [report](https://github.com/yisibl/resvg-js/issues/321) for version 2.6.1 which has been fixed in 2.6.2 however from the changes in the [MR](https://github.com/yisibl/resvg-js/pull/322) I was unable to identify the required changes to fix the issue since the files in the MR are auto-generated if I'm not mistaken. 

Background: I'm trying to upgrade resvg to 0.44.0 since CSS injection support has been added recently (and also experiment with the [SIMD features](https://github.com/yisibl/resvg-js/pull/148) / [type features](https://github.com/yisibl/resvg-js/pull/304)).

**Comment by David-Development** [comment]
Forgot to update the corresponding js files in the web projects since I was importing them through the npm dependency.. Sorry 🤦‍♂️

**Comment by yisibl** [comment]
That's okay, glad to see you trying and exploring.
