### ISSUE TITLE
Support WebAssembly (wasm)

### ISSUE THREAD

**Issue by styfle** [yisibl/resvg-js#48]
This looks like a really great project, thanks!

I saw wasm on the roadmap in the readme so I thought I would create an issue to show support for this feature request 🙂 

I'm interested in running resvg with a browser, with Node.js, and with other edge-compute tools.

**Comment by yisibl** [comment]
Thanks for your feedback, I have plans to support WASM.

It is relatively easy to implement via `wasm-bindgen`, are you interested in PR?

**Comment by yisibl** [comment]
Welcome @zimond  joined the **resvg-js** project. He will implement WASM support.

**Comment by yisibl** [comment]
@styfle  Do you need to load custom fonts and system fonts in the WASM version?

**Comment by styfle** [comment]
Yes. Although if its hard to get system fonts working, only custom fonts would be acceptable 👍

**Comment by shuding** [comment]
It would be great if custom font support can be optional (wasm-lite and wasm-full), is that possible?

**Comment by yisibl** [comment]
> It would be great if custom font support can be optional (wasm-lite and wasm-full), is that possible?

I will investigate the feasibility in version 2.0.

**Comment by yisibl** [comment]
The wasm version can now be previewed online: https://resvg-js.vercel.app

**Comment by yisibl** [comment]
v2.0.0-alpha.0 has been released. https://github.com/yisibl/resvg-js/releases/tag/v2.0.0-alpha.0

**Comment by yisibl** [comment]
Note: We are in the process of refactoring the API(https://github.com/yisibl/resvg-js/pull/72), and there may be more significant changes when v2 is released. Feel free to give us feedback on your suggestions.

**Comment by yisibl** [comment]
Wasm has been released in 2.0.
