### ISSUE TITLE
Cannot render <image> node. Both external and embedded image.

### ISSUE THREAD

**Issue by suyuan-chang** [yisibl/resvg-js#76]
Thank you! This is a great project.
But after a quick evaluation, it seems that resvg-js does not support `<image>` in `<svg>`. Both external and embedded image does not work. This is a know issue or a bug, or I use it wrong?

Example:
```
    <svg width="200" height="200"
        xmlns="http://www.w3.org/2000/svg">
        <image 
            href=
"https://media.geeksforgeeks.org/wp-content/cdn-uploads/20190710102234/download3.png" 
            height="200" width="200"/>
    </svg>
```

**Comment by yisibl** [comment]
Upstream resvg does not support network requests yet. See also: https://github.com/RazrFalcon/resvg/issues/479#issuecomment-965579048

However, custom xlink:href resolver has been implemented in https://github.com/RazrFalcon/resvg/pull/498 , which requires reading the bitmap yourself.

**Comment by suyuan-chang** [comment]
Thanks for asking my question.
If resvg-js doesn't support custom href resolver yet, I can help to implement this. Maybe I will bridge the custom href resolver to fetch() API and use web browser to issue network requests.

**Comment by zimond** [comment]
Actually in our production, we expose a general `usvg::NodeKind` API to manipulate various nodes in a usvg tree. So this problem could be easily solved by iterating over image nodes, read, fetch and write `xlink:href`. Maybe this will be added in a future version of resvg-js, if needed.

**Comment by azf20** [comment]
This would be an amazing addition - was trying this out in node.js but needed to import external images by URL
