### ISSUE TITLE
Error reported in Node.js 12: Segmentation fault

### ISSUE THREAD

**Issue by yisibl** [yisibl/resvg-js#83]
https://github.com/svg-sprite/svg-sprite/pull/606
https://github.com/svg-sprite/svg-sprite/runs/5538012701?check_suite_focus=true

```bash
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! svg-sprite@2.0.0-beta2 mocha: `mocha "test/**/*.test.js"`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the svg-sprite@2.0.0-beta2 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by yisibl** [comment]
Dependent on: https://github.com/nodejs/node/issues/42376

**Comment by Kreeg** [comment]
Hello @yisibl 
I think it's fixed now :)

**Comment by yisibl** [comment]
Yes, this was fixed in Node.js 12.22.12(https://github.com/nodejs/node/pull/42531)
