### ISSUE TITLE
Transparent Backgrounds

### ISSUE THREAD

**Issue by TheOtterlord** [yisibl/resvg-js#95]
First off, thanks for the great library, it's been really useful in my current project.

I'm not sure if this a bug or feature request, but I'm unable to specify a completely transparent background which makes it harder to work with SVGs such as icons that don't always have a complete background

**Comment by yisibl** [comment]
Demo or svg code？


------------------ Original ------------------
From: Reuben Tier ***@***.***&gt;
Date: Sat,Apr 2,2022 5:18 AM
To: yisibl/resvg-js ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [yisibl/resvg-js] Transparent Backgrounds (Issue #95)





 
First off, thanks for the great library, it's been really useful in my current project.
 
I'm not sure if this a bug or feature request, but I'm unable to specify a completely transparent background which makes it harder to work with SVGs such as icons that don't always have a complete background

**Comment by TheOtterlord** [comment]
Never mind. While recreating the issue I discovered Firefox was to blame. It for some reason places an off-white background underneath svgs when previewing alone in the browser :rofl:. Thanks for the quick response regardless.
Sorry for the confusion, I'll close this issue now.
